name: Java CI with Gradle

# Workflow‑weite Default‑Berechtigungen: nur Lesen
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read       # nur Checkout & Tests
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Build & Test
        run: ./gradlew build

  dependency-submission:
    name: Submit Dependency Graph
    # läuft nur bei Push auf main
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write      # benötigt für Submission
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
