name: Java CI with Gradle

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Test
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    # Job läuft immer, egal ob push oder PR
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate and submit dependency graph
        if: github.event_name == 'push'
        uses: gradle/actions/dependency-submission@v4
